Add proper documentation.

diff --git a/bin/puma-add b/bin/puma-add
--- a/bin/puma-add
+++ b/bin/puma-add
@@ -1,4 +1,5 @@
 #!/bin/bash
+# Script to simplify adding a new user/pass combination
 #
 # This file is part of PUMA.
 # Copyright 2017 Bennett Piater and Justus Piater
@@ -16,10 +17,13 @@
 # You should have received a copy of the GNU General Public License
 # along with PUMA.  If not, see <http://www.gnu.org/licenses/>.
 
+#PUMA_GPGID="${PUMA_GPGID:-bennett@piater.name}"
+PUMA_KEYRING="${PUMA_KEYRING:-$HOME/Documents/keyring}"
+
 if [[ x"$1" = x"--random" ]]; then
 	IFS="|" read -r FNAME USER < <(zenity --title "Add a new user" --forms --text="Add a new user with random password" --add-entry=filename --add-entry=user)
-	PASS=$(diceware)
-	printf "%s" "$PASS" | xclip  # Copy the randomly-generated password to the clipboard
+	PASS=$(diceware) || exit 1
+	#printf "%s" "$PASS" | xclip  # Copy the randomly-generated password to the clipboard
 else
 	IFS="|" read -r FNAME USER PASS < <(zenity --title "Add a new user" --forms --text="Add a new user" --add-entry=filename --add-entry=user --add-password=pass)
 fi
@@ -29,11 +33,10 @@ if [[ -z "$FNAME" || -z "$USER" || -z "$PASS" ]]; then
 	exit 1
 fi
 
-FILENAME="$HOME"/Documents/keyring/"$FNAME"
+FILENAME="$PUMA_KEYRING"/"$FNAME"
 
-printf "User: %s\nPass: %s\n" "$USER" "$PASS" >"$FILENAME"
-
-gpg --batch --yes --encrypt --recipient bennett@piater.name "$FILENAME" || zenity --error --text "gpg error!"
+cat <<< "User: $USER"$'\n'"Pass: $PASS"$'\n' >"$FILENAME"
+gpg --batch --yes --encrypt --recipient "$PUMA_GPGID" "$FILENAME" || { zenity --error --text "gpg error!"; exit 1; }
 
 rm -f "$FILENAME"
 
